/*****************************************************************************
 *
 * Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
 * Produced at the Lawrence Livermore National Laboratory
 * LLNL-CODE-442911
 * All rights reserved.
 *
 * This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
 * full copyright notice is contained in the file COPYRIGHT located at the root
 * of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
 *
 * Redistribution  and  use  in  source  and  binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of  source code must  retain the above  copyright notice,
 *    this list of conditions and the disclaimer below.
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
 *    documentation and/or other materials provided with the distribution.
 *  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
 *    be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
 * ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
 * LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
 * DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
 * CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
 * LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
 * OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 *****************************************************************************/

// ************************************************************************* //
//                            avtMeshFileFormat.C                           //
// ************************************************************************* //

#include <avtMeshFileFormat.h>

#include <string>
#include <sstream>
#include <limits>

#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>
#include <vtkCellType.h>
#include <vtkIdList.h>

using     std::string;


// ****************************************************************************
//  Method: avtMeshFileFormat constructor
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Tue Nov 26 23:20:14 PST 2013
//
// ****************************************************************************

    avtMeshFileFormat::avtMeshFileFormat(const char *filename)
: avtSTSDFileFormat(filename)
{
    m_filename = filename;
    m_pointsData = vtkPoints::New();
    m_grid = vtkUnstructuredGrid::New();
    m_var = vtkFloatArray::New();
    
}


// ****************************************************************************
//  Method: avtMeshFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Tue Nov 26 23:20:14 PST 2013
//
// ****************************************************************************

    void
avtMeshFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtMeshFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Tue Nov 26 23:20:14 PST 2013
//
// ****************************************************************************

    void
avtMeshFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
    avtMeshMetaData * mesh = new avtMeshMetaData;
    mesh->name = "mesh";
    mesh->meshType = AVT_POINT_MESH;
    mesh->numBlocks = 1;
    mesh->blockOrigin = 0;
    mesh->spatialDimension = 3;
    mesh->topologicalDimension = 2;
    mesh->hasSpatialExtents= false;
    md->Add(mesh);

    //if(random ass check)
    AddScalarVarToMetaData(md, "nope", "mesh", AVT_NODECENT, NULL);
}


// ****************************************************************************
//  Method: avtMeshFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Tue Nov 26 23:20:14 PST 2013
//
// ****************************************************************************

    vtkDataSet *
avtMeshFileFormat::GetMesh(const char *meshname)
{
    ReadData();

    // Update the pointer count and return
    m_grid->Register(NULL);
    return m_grid;
}


// ****************************************************************************
//  Method: avtMeshFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Tue Nov 26 23:20:14 PST 2013
//
// ****************************************************************************

    vtkDataArray *
avtMeshFileFormat::GetVar(const char *varname)
{
    ReadData();

    // Set the data array to our read variable
    vtkDataArray * rv = m_var;

    // Adjust the pointer count and return
    rv->Register(NULL);
    return rv;
}

void avtMeshFileFormat::ReadData()
{
    std::ifstream ifile(m_filename);
    if(ifile == NULL) return;

    std::string line, tmp;
    std::stringstream ss;

    int nbVertices = 0, nbTriangles = 0;
    bool gotNbVertices = false, gotNbTriangles = false;

    std::getline(ifile, line);

    // Making sure we have the right number of vertices
    if(!gotNbVertices)
    {
        while(line.find("Vertices") == string::npos)
            std::getline(ifile, line);

        std::getline(ifile, line);
        ss << line;
        ss >> nbVertices;
        gotNbVertices = true;
    }

    // Getting points data
    double x, y, z, v;
    std::cout.precision(18);
    for(int i = 0; i < nbVertices; i++)
    {
        std::getline(ifile, line);
        ss.clear();
        ss << line;

        ss >> x;
        ss >> y;
        ss >> z;
        ss >> v;

        m_pointsData->InsertNextPoint(x,y,z);
    }

    m_grid->SetPoints(m_pointsData);
    m_pointsData->Delete();

    // Getting triangles data
    std::getline(ifile, line); // "Triangles"
    std::getline(ifile, line); // Number of triangles
    ss.clear();
    ss << line;
    ss >> nbTriangles;

    float next;
    for(int i = 0; i < nbTriangles; i++)
    {
        vtkIdList* trianglesIds = vtkIdList::New();
        std::getline(ifile, line);
        ss.clear();
        ss << line;

        ss >> x;
        ss >> y;
        ss >> z;
        ss >> next;

        trianglesIds->SetNumberOfIds(3);
        trianglesIds->SetId(0, x - 1);
        trianglesIds->SetId(1, y - 1);
        trianglesIds->SetId(2, z - 1);

        m_grid->InsertNextCell(VTK_TRIANGLE, trianglesIds);
        m_var->InsertNextTuple1(next);
    }
}

// ****************************************************************************
//  Method: avtMeshFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Tue Nov 26 23:20:14 PST 2013
//
// ****************************************************************************

    vtkDataArray *
avtMeshFileFormat::GetVectorVar(const char *varname)
{
}
